### ISSUE TITLE
Sed homework due 10/3 for Courtney Blomme

### ISSUE THREAD

**Issue by courtneyblomme** [courtneyblomme/stat679-notes#2]
Hi @cecileane and @coraallencoleman,

For the homework due today and described [here](https://github.com/UWMadison-computingtools-master/lecture-examples/tree/master/tableofSNPs), I submit the following one-liner solutions.

To modify the values in the minimum column:
`sed -E 's/\"([0-9]+),([0-9]+),?([0-9]*)\"/\1\2\3/' tableofSNPs.csv > tableofSNPs_cleaned.csv`

To check that each line only has 3 commas:
`sed 's/[^,]//g' tableofSNPs_cleaned.csv | sort | uniq`

As always, any feedback is welcomed!

Best,

Courtney

**Comment by cecileane** [comment]
perfect!
